name: Publish Release
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - uses: gradle/gradle-build-action@v2.4.2
      - run: gradle assembleRelease
      - uses: actions/upload-artifact@v3.1.1
        with:
            name: github-${{ github.sha }}
            path: app/build/outputs/apk/github/release/*.apk